/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/culture` | `/culture`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/enhance` | `/enhance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hustle` | `/hustle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/subscription` | `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/culture` | `/culture`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/enhance` | `/enhance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/hustle` | `/hustle`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/subscription` | `/subscription`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/notifications${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/culture${`?${string}` | `#${string}` | ''}` | `/culture${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/enhance${`?${string}` | `#${string}` | ''}` | `/enhance${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/hustle${`?${string}` | `#${string}` | ''}` | `/hustle${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/skills${`?${string}` | `#${string}` | ''}` | `/skills${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/subscription${`?${string}` | `#${string}` | ''}` | `/subscription${`?${string}` | `#${string}` | ''}` | `/auth/SignUp${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/culture` | `/culture`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/enhance` | `/enhance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hustle` | `/hustle`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/skills` | `/skills`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/subscription` | `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `/auth/SignUp`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
